apiVersion: v1
kind: BuildConfig
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: >-
        http://tfs-prod1.service.raiffeisen.ch:8080/tfs/RCH/AP.Trading_ZB_Systeme/_git/toeggli-web
      ref: master
    sourceSecret:
      name: rch-git-basic-auth
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nodejs-8-rhel7:latest'
      env:
        - name: LSG_EXT_BUILDS
          value: 'abt,prd'
  output:
    to:
      kind: ImageStreamTag
      name: 'frontend:latest'
  resources:
    limits:
      cpu: 4
      memory: 1G
    requests:
      cpu: 1
      memory: 500M
  nodeSelector: null
